version: '3'

services:
  db:
    image: mysql:8.0.31
    ports:
      - "3306:3306"
    volumes:
      - /opt/software/mysql/conf:/etc/mysql/conf.d
      - /opt/software/mysql/data:/var/lib/mysql
      - /opt/software/mysql/logs:/logs
    environment:
      - MYSQL_ROOT_PASSWORD=LHY18337580372
      - TZ=Asia/Shanghai
    restart: always
  redis:
    image: redis:6.2.10
    ports:
      - "6379:6379"
    volumes:
      - /opt/software/redis/redis.conf:/etc/redis/redis.conf
      - /opt/software/redis/data:/data
    command: redis-server /etc/redis/redis.conf
    restart: always
  snowflake:
    build: ./snowflake
    ports:
      - "8910:8910"
    volumes:
      - ./snowflake:/app
    restart: always
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    command: uwsgi --ini /code/uwsgi.ini
    depends_on:
      - snowflake
      - redis
      - db
    restart: always